networks:
  lendmate-net:
    external: true

services:
  product-service:
    image: "product-service"
    build: .
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_service_db
      SPRING_DATASOURCE_USERNAME: lendmate
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: product-service
      AWS_ACCESS_KEY_ID: AKIAT25QXJXDR3JVEHWM
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: us-east-1
      CONFIG_SERVER_URL: http://config-server:8888
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=55.0 
        -XX:+UseSerialGC 
        -Xss256k 
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
    mem_limit: 450m
    restart: unless-stopped
    networks:
      - lendmate-net

volumes:
  postgres_data: