networks:
  lendmate-net:
    external: true

services:
  product-service:
    image: "product-service"
    build: .
    container_name: product-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - lendmate-net

volumes:
  postgres_data: