spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_db_dev
    username: lendmate
    password: lendmate
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  elasticsearch:
    uris: http://localhost:9200
    repositories:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.project.lendmate.event.StockDecreaseEvent

logging:
  level:
    com:
      project:
        lendmate: DEBUG

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
  resource:
    attributes:
      service.name: ${spring.application.name}
  logs:
    exporter: otlp
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  java:
    disabled:
      resource:
        providers: io.opentelemetry.instrumentation.resources.ProcessResourceProvider
