spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lendmate_dev
    username: devuser
    password: devpass
  jpa:
    show-sql: true

logging:
  level:
    com:
      project:
        lendmate: DEBUG

