spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service_db_dev
    username: lendmate
    password: lendmate
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  elasticsearch:
    uris: http://localhost:9200
    repositories:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com:
      project:
        lendmate: DEBUG

