spring:
  jpa:
    show-sql: false
#  data:
#    redis:
#      host: redis
#      port: 6379

  elasticsearch:
    uris: http://elasticsearch:9200
    repositories:
      enabled: false

  kafka:
    bootstrap-servers: lendmate-kafka:9092
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.project.lendmate.event.StockDecreaseEvent

management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator / metrics / health endpointlerini dışarı açar
  metrics:
    tags:
      # Grafana dashboard'larının uygulamayı ayırt etmesi için service.name şarttır
      application: ${spring.application.name:product-service}
  tracing:
    sampling:
      probability: 1.0

server:
  shutdown: immediate

logging:
  level:
    com.project: INFO