springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework

spring:
  application:
    name: lendmate
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate

aws:
  accessKeyId: AKIAT25QXJXDR3JVEHWM
  secretAccessKey: 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
  region: us-east-1





